In [1]:
from sklearn.linear_model import Perceptron
x=[[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model=Perceptron()
model.fit(x,y)
model.score(x,y)
x1=[[0.5,0],[0,0.5],[0.6,0],[0,0.6],[-10,2],[0.1,1],[-0.3,4]]
y1=model.predict(x1)
print(y1)

[0 0 1 1 0 1 1]


In [2]:
from sklearn.linear_model import Perceptron
x=[[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
y=[1,1,0,0]
model=Perceptron()
model.fit(x,y)
model.score(x,y)
x2=[[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
y2=model.predict(x2)
print(y2)

[1 1 0 0]


In [3]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

iris=datasets.load_iris()
x=iris.data
y=iris.target
print(x[:5])
print(y[:5])

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
sc=StandardScaler()
sc.fit(x_train)
x_train_std=sc.transform(x_train)
x_test_std=sc.transform(x_test)
print(x_train,x_train_std)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[[6.6 3.  4.4 1.4]
 [6.5 3.  5.2 2. ]
 [5.4 3.  4.5 1.5]
 [7.1 3.  5.9 2.1]
 [6.7 3.  5.2 2.3]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.9 0.4]
 [7.2 3.6 6.1 2.5]
 [5.2 4.1 1.5 0.1]
 [4.6 3.6 1.  0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [7.9 3.8 6.4 2. ]
 [5.8 2.7 3.9 1.2]
 [5.6 2.8 4.9 2. ]
 [6.1 2.8 4.  1.3]
 [5.4 3.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]
 [7.7 2.8 6.7 2. ]
 [4.4 3.  1.3 0.2]
 [5.8 2.7 5.1 1.9]
 [4.6 3.1 1.5 0.2]
 [6.1 2.9 4.7 1.4]
 [4.8 3.1 1.6 0.2]
 [6.7 3.3 5.7 2.1]
 [5.1 3.3 1.7 0.5]
 [4.5 2.3 1.3 0.3]
 [5.8 2.6 4.  1.2]
 [6.7 3.1 5.6 2.4]
 [6.  2.7 5.1 1.6]
 [4.8 3.  1.4 0.1]
 [5.1 3.8 1.5 0.3]
 [5.1 3.8 1.6 0.2]
 [6.9 3.1 5.4 2.1]
 [5.5 3.5 1.3 0.2]
 [4.8 3.4 1.6 0.2]
 [4.6 3.4 1.4 0.3]
 [5.9 3.  4.2 1.5]
 [4.7 3.2 1.3 0.2]
 [6.4 3.2 4.5 1.5]
 [6.4 2.8 5.6 2.2]
 [5.  2.3 3.3 1. ]
 [6.  3.4 4.5 1.6]
 [5.7 2.8 4.5 1.3]
 [6.9 3.1 4.9 1.5]
 [5.8 2.8 5.1 2.4]
 [4.9 3.6 1.4 0.1]

In [4]:
model=Perceptron(max_iter=1000,eta0=0.1,random_state=0)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)
print(y_test)
print('Do chinh xac cua mo hinh chua Scale:',accuracy_score(y_test,y_pred))

[0 1 2 0 1 1 1 1 1 1 0 2 2 1 0 2 1 0 2 1 2 2 0 2 1 0 1 0 2 0 2 1 2 2 2 1 0
 0 0 2 0 1 0 1 0]
[0 1 2 0 1 1 1 1 1 1 0 2 2 2 0 2 1 0 2 1 2 2 0 2 1 0 1 0 2 0 2 1 2 2 2 1 0
 0 0 2 0 1 0 2 0]
Do chinh xac cua mo hinh chua Scale: 0.9555555555555556


In [5]:
model=Perceptron(max_iter=1000,eta0=0.1,random_state=0)
model.fit(x_train_std,y_train)
y_pred=model.predict(x_test_std)
print(y_pred)
print(y_test)
print('Do chinh xac cua mo hinh:',accuracy_score(y_test,y_pred))

[0 1 2 0 1 1 1 1 1 1 0 2 1 1 0 1 1 0 1 1 2 2 0 2 1 0 1 0 1 0 2 1 1 2 2 1 0
 0 0 1 0 1 0 1 0]
[0 1 2 0 1 1 1 1 1 1 0 2 2 2 0 2 1 0 2 1 2 2 0 2 1 0 1 0 2 0 2 1 2 2 2 1 0
 0 0 2 0 1 0 2 0]
Do chinh xac cua mo hinh: 0.8222222222222222


In [7]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
url = '/content/crabs.csv'
DataFrame = pd.read_csv(url)

print(DataFrame)

    speies sex  index  fontallip  rearwidth  length  width  depth
0        B   M      1        8.1        6.7    16.1   19.0    7.0
1        B   M      2        8.8        7.7    18.1   20.8    7.4
2        B   M      3        9.2        7.8    19.0   22.4    7.7
3        B   M      4        9.6        7.9    20.1   23.1    8.2
4        B   M      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      O   F     46       21.4       18.0    41.2   46.2   18.7
196      O   F     47       21.7       17.1    41.7   47.2   19.6
197      O   F     48       21.9       17.2    42.6   47.4   19.5
198      O   F     49       22.5       17.2    43.0   48.7   19.8
199      O   F     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [8]:
DataFrame['speies'].replace({"B":"0","O":"1"},inplace=True)
DataFrame['sex'].replace({"F":"0","M":"1"},inplace=True)
print(DataFrame)

    speies sex  index  fontallip  rearwidth  length  width  depth
0        0   1      1        8.1        6.7    16.1   19.0    7.0
1        0   1      2        8.8        7.7    18.1   20.8    7.4
2        0   1      3        9.2        7.8    19.0   22.4    7.7
3        0   1      4        9.6        7.9    20.1   23.1    8.2
4        0   1      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      1   0     46       21.4       18.0    41.2   46.2   18.7
196      1   0     47       21.7       17.1    41.7   47.2   19.6
197      1   0     48       21.9       17.2    42.6   47.4   19.5
198      1   0     49       22.5       17.2    43.0   48.7   19.8
199      1   0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [9]:
DataFrame= datasets.load_iris()
x= DataFrame.data
y = DataFrame.target
print(x[:5])
print(y[:5])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
sc=StandardScaler()
sc.fit(x_train)
x_train_std=sc.transform(x_train)
x_test_std=sc.transform(x_test)
print(x_train_std[:5],x_train[:5])
print(y[:5])

model = Perceptron(max_iter=1000,eta0=0.4,random_state=0)
#max_iter : so lan hoc
#eta0 toc do hoc
model.fit(x_train_std,y_train)
y_pred=model.predict(x_test_std)

print(y_pred)
print(y_test)
print("Do chinh xac mo hinh:",accuracy_score(y_test,y_pred))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[[ 1.36349779  0.12126946  0.78044845  1.43192973]
 [-1.55828318  0.12126946 -1.34039637 -1.35729735]
 [-0.16090968 -0.10212165  0.25023725 -0.02909398]
 [-0.54201154 -0.10212165  0.42697431  0.36936703]
 [-0.92311341  1.68500722 -1.28148401 -1.35729735]] [[6.9 3.1 5.1 2.3]
 [4.6 3.1 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [5.4 3.  4.5 1.5]
 [5.1 3.8 1.6 0.2]]
[0 0 0 0 0]
[0 2 1 0 0 2 1 1 0 2 0 2 1 2 1 1 0 0 1 2 0 1 1 0 1 0 2 2 1 1 0 0 0 1 2 0 2
 2 0 2 0 0 2 2 2]
[0 2 0 0 0 2 1 1 0 2 0 2 1 2 1 1 0 0 1 2 0 1 1 0 1 0 2 2 2 1 1 0 0 1 2 0 1
 2 0 2 0 0 2 2 2]
Do chinh xac mo hinh: 0.9111111111111111
